# Juicer configuration file
juicer:
    debug: true
    servers:
        redis_url: redis://redis:6379
    services:
        tahiti:
            url: http://tahiti:23403
            #auth_token: Wl1ba1j57f
            auth_token: '123456'
        limonero:
            url: http://beta.ctweb.inweb.org.br/limonero #http://limonero:23402
            #url: http://limonero:23402
            #auth_token: 7F6LVA18h8
            auth_token: '123456'
        caipirinha:
            url: http://caipirinha:23401
            # auth_token: Z81D5te0w1
            auth_token: '123456'
            storage_id: 2
    config:
        tmp_dir: /tmp
    spark:
        # For more information, see http://spark.apache.org/docs/latest/configuration.html
        spark.executor.memory: 4g
        spark.executor.cores: 3
        spark.cores.max: 3
        spark.driver.memory: 4g
        # Allowed URLS:
        # local:                Run locally with 1 worker thread
        # local[k]:             Run locally with k worker threads
        # local[*]:             Run locally with as many worker threads as logical cores
        # spark://host:port:    Connect to Spark standalone cluster (default port 7077)
        # mesos://host:port:    Connect to Mesos cluster (default port 5050)
        # yarn:                 Connect to Yarn cluster. Cluster location will be found based
        #                       on the HADOOP_CONF_DIR or YARN_CONF_DIR variable.
        spark.master: local[*]

        spark.localdir: /tmp
        # spark.submit.deployMode: client
        spark.driver.extraClassPath: null
        spark.executor.extraClassPath: null
        spark.jars: null
        spark.eventLog.enabled: true
        spark.eventLog.dir: hdfs://spark01.ctweb.inweb.org.br:9000/lemonade-spark-events 
        #spark.history.fs.logDirectory: hdfs://spark01.ctweb.inweb.org.br:9000/lemonade-spark-events
