# Stand configuration file
stand:
    debug: false
    #secret: sg7qS1ENqN
    secret: "123456"
    port: 23404
    environment: prod
    servers:
        database_url: mysql+pymysql://root:lemon@mysql/stand
        redis_url: redis://redis:6379
    services:
        thorn:
            url: http://thorn:23405
    config:
        SQLALCHEMY_POOL_SIZE: 0
        SQLALCHEMY_POOL_RECYCLE: 60

