# Tahiti configuration file
tahiti:
    debug: false
    environment: prod
    secret: 123456
    port: 23403
    servers:
        database_url: mysql+pymysql://root:lemon@mysql/tahiti?charset=utf8
    services:
        thorn:
            url: http://thorn:3000
    config:
        SQLALCHEMY_POOL_SIZE: 0
        SQLALCHEMY_POOL_RECYCLE: 60

